version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: bookrent
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bookrent
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  book-service:
    build:
      context: ./services/book-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  auth-service:
    build:
      context: ./services/auth-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  rental-service:
    build:
      context: ./services/rental-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - rabbitmq

  notification-service:
    build:
      context: ./services/notification-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - rabbitmq

volumes:
  pgdata:
